#!/bin/bash

_oldVer=$(source PKGBUILD && echo $pkgver)
makepkg -o -d
_newVer=$(source PKGBUILD && echo $pkgver)

if [ "$_oldVer" != "$_newVer" ]; then
    archlinuxcn-$(uname -m)-build -r /data/$2 || archlinuxcn-$(uname -m)-build -c -r /data/$2 || exit 1
    sign-package $1 || exit 1
    copy-package $1 || exit 1
    rsync-package $1 || exit 1
fi
