#!/bin/bash

repo=$HOME/public_html/deepincn/$1/os/$2

package=($(ls | grep -i "zst$") $(ls | grep -i "xz$"))

cd $repo

for zst in ${package[*]}
do
    flock $HOME/.cache/$1.db.lck repo-add -R deepincn.db.tar.xz $zst || exit 1
done