#!/bin/bash

package=($(ls | grep -i "zst$") $(ls | grep -i "xz$"))

cd ~/deepincn/$1/os/$(uname -m)

for zst in ${package[*]}
do
    flock /tmp/git.db.lck repo-add -R deepincn.db.tar.xz $zst || exit 1
done
